name: Docker Image CI

on:
  push:
    branches: [ "master", "sandbox", "production" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the DockerDep image
      run: docker build . --file Dockerfile.dep --tag example1dep:$(date +%s)
    - name: DockerDep Push
      run: docker push example1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag example1:$(date +%s)
    - name: Docker Push
      run: docker push example1
